#require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/avalon/batch/manifest.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false
